Update postinstall

diff --git a/scripts/postinstall b/scripts/postinstall
--- a/scripts/postinstall
+++ b/scripts/postinstall
@@ -12,13 +12,10 @@ sudo curl -L "$GITHUB_REPO_URL" --output "$CEP_EXTENSIONS_DIR/com.selgy.youtubet
 
 echo "Installing com.selgy.youtubetopremiere..."
 sudo unzip -o "$CEP_EXTENSIONS_DIR/com.selgy.youtubetopremiere.zip" -d "$CEP_EXTENSIONS_DIR" && echo "Unzip successful." || { echo "Unzip failed"; exit 1; }
-
-# Check if the directory already exists and remove it if necessary
-if [ -d "$CEP_EXTENSIONS_DIR/com.selgy.youtubetopremiere" ]; then
-    sudo rm -rf "$CEP_EXTENSIONS_DIR/com.selgy.youtubetopremiere"
-fi
-
 sudo mv "$CEP_EXTENSIONS_DIR/Youtube-to-PremierePro-Pre-released/com.selgy.youtubetopremiere" "$CEP_EXTENSIONS_DIR/com.selgy.youtubetopremiere" && echo "Move successful." || { echo "Failed to move directory"; exit 1; }
+
+# Delete the intermediate folder from GitHub
+sudo rm -rf "$CEP_EXTENSIONS_DIR/Youtube-to-PremierePro-Pre-released" && echo "Intermediate folder deleted successfully." || { echo "Failed to delete intermediate folder"; exit 1; }
 
 # Delete the downloaded ZIP file
 sudo rm "$CEP_EXTENSIONS_DIR/com.selgy.youtubetopremiere.zip" && echo "ZIP file deleted successfully." || { echo "Failed to delete ZIP file"; exit 1; }
@@ -30,10 +27,13 @@ sudo mkdir -p "$EXEC_DIR" && echo "Exec directory created successfully." || { ec
 echo "Copying executable to $EXEC_DIR..."
 sudo cp -R "$EXECUTABLE_PATH/"* "$EXEC_DIR" && echo "Executable copied successfully." || { echo "Failed to copy executable"; exit 1; }
 
-if [ -d "$EXEC_DIR/YoutubetoPremiere" ]; then
-    echo "com.selgy.youtubetopremiere installed successfully."
+# Set execution permission for ffmpeg
+FFMPEG_PATH="$EXEC_DIR/_internal/ffmpeg/bin/ffmpeg"
+if [ -f "$FFMPEG_PATH" ]; then
+    echo "Setting execution permission for ffmpeg..."
+    sudo chmod +x "$FFMPEG_PATH" && echo "Execution permission set successfully." || { echo "Failed to set execution permission for ffmpeg"; exit 1; }
 else
-    echo "Error: Failed to copy the executable."
+    echo "ffmpeg file not found at $FFMPEG_PATH."
 fi
 
 echo "Cleanup started..."
