Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,36 +8,28 @@ on:
 jobs:
   mac-build:
     runs-on: macos-latest
-  
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
-  
+
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8.8
-  
+
     - name: Cache pip
       uses: actions/cache@v2
       with:
-        path: ~/Library/Caches/pip
-        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-  
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '14'
-        
-    - name: Install Adobe CEP ZXP Packager
-      run: npm install -g create-zxp
-  
+          path: ~/Library/Caches/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+
     - name: Upgrade pip
       run: python -m pip install --upgrade pip
-  
+
     - name: Install dependencies
       run: pip install -r requirements.txt
-  
+
     - name: Check FFmpeg installation
       run: |
         if brew list --versions ffmpeg > /dev/null; then
@@ -48,50 +40,74 @@ jobs:
           echo "FFmpeg is not installed. Installing it now..."
           brew install ffmpeg
         fi
-  
+
     - name: Install PyInstaller
       run: pip install pyinstaller
-  
+
     - name: Build Application with PyInstaller
       run: |
-          # Continue with PyInstaller
-          pyinstaller --onefile --clean --windowed --debug all \
-            --hidden-import=engineio.async_drivers.eventlet \
-            --hidden-import=engineio.async_drivers.gevent_uwsgi \
-            --hidden-import=engineio.async_drivers.gevent \
-            --hidden-import=engineio.async_drivers \
-            --hidden-import=gevent \
-            --hidden-import=engineio.async_drivers.threading \
-            --hidden-import=pygame.freetype \
-            --hidden-import=encodings.utf_16_le \
-            --add-data "./icon.png:." \
-            --add-data "./notification_sound.mp3:." \
-            --icon "./icon.icns" \
-            YoutubetoPremiere.py
+        pyinstaller --onefile --clean --windowed --debug all \
+        --hidden-import=engineio.async_drivers.eventlet \
+        --hidden-import=engineio.async_drivers.gevent_uwsgi \
+        --hidden-import=engineio.async_drivers.gevent \
+        --hidden-import=engineio.async_drivers \
+        --hidden-import=gevent \
+        --hidden-import=engineio.async_drivers.threading \
+        --hidden-import=pygame.freetype \
+        --hidden-import=encodings.utf_16_le \
+        --add-data "./icon.png:." \
+        --add-data "./notification_sound.mp3:." \
+        --icon "./icon.icns" \
+        YoutubetoPremiere.py
 
 
-    - name: Prepare PymiereLink folder
+    - name: Prepare FFmpeg directory
       run: |
-              mkdir -p ./PymiereLink/
-              mkdir -p ./PymiereLink/exec
-              mv "./dist/YoutubetoPremiere.app/Contents/MacOS/YoutubetoPremiere" "./PymiereLink/exec/"
-              cp -R /usr/local/Cellar/ffmpeg/6.0_1 "./PymiereLink/exec/ffmpeg"
-      
-    - name: Zip PackageContents folder
+          mkdir -p "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink/exec/"
+          echo "Listing contents of temp ffmpeg directory:"
+          ls -la "./ffmpeg"
+        
+    - name: Move FFmpeg to the exec folder
       run: |
-            cd PymiereLink
-            zip -r ../YoutubetoPremiere_Mac.zip ./
-            cd ..
-            
-    - name: Zip to ZXP
-      run: mv YoutubetoPremiere_Mac.zip YoutubetoPremiere_Mac.zxp      
+          mv "./ffmpeg" "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink/exec/"
+          else
+            echo "FFmpeg directory is empty or does not exist."
+            exit 1
+          fi
 
-    - name: Find YoutubetoPremiere_Mac.zxp
-      run: find . -name "YoutubetoPremiere_Mac.zip"
-      
-    - name: List directory contents
-      run: ls -R ./dist/YoutubetoPremiere.app/Contents/Resources/
-      
+    - name: Prepare PymiereLink and Installation Script
+      run: |
+        mkdir -p "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink"
+        cp -R "/path/to/PymiereLink" "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink"
+        cp "install_pymierelink.sh" "./dist/YoutubetoPremiere.app/Contents/Resources/"
+
+        if [ -f "./dist/YoutubetoPremiere.app/Contents/MacOS/YoutubetoPremiere" ]; then
+          mv "./dist/YoutubetoPremiere.app/Contents/MacOS/YoutubetoPremiere" "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink/exec"
+        else
+          echo "Executable not found. Check PyInstaller build process."
+          exit 1
+        fi
+
+    - name: Create macOS Package
+      run: |
+        # Define installation location and package identifier
+        INSTALL_LOCATION="/Library/Application Support/Adobe/CEP/extensions/PymiereLink"
+        PACKAGE_ID="com.selgy.youtubetopremiere"
+
+        # Create a temporary package root directory
+        mkdir -p ./pkgroot"$INSTALL_LOCATION"
+
+        # Copy files to the package root directory
+        cp -R "./dist/YoutubetoPremiere.app" "./pkgroot$INSTALL_LOCATION"
+
+        # Build the package
+        pkgbuild --root "./pkgroot" \
+                --identifier "$PACKAGE_ID" \
+                --install-location "$INSTALL_LOCATION" \
+                --version "1.0" \
+                --ownership "recommended" \
+                "YoutubetoPremiere.pkg"
+
     - name: Get the release
       id: get_release
       uses: actions/github-script@v5
@@ -106,13 +122,13 @@ jobs:
       id: upload-release-asset
       uses: softprops/action-gh-release@v1
       env:
-        GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
+            GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
       with:
-        draft: ${{ github.ref == 'refs/heads/master' }}
-        prerelease: ${{ github.ref != 'refs/heads/master' }}
-        tag_name: V1.1
-        files: |
-          ./YoutubetoPremiere_Mac.zxp
+            draft: ${{ github.ref == 'refs/heads/master' }}
+            prerelease: ${{ github.ref != 'refs/heads/master' }}
+            tag_name: V1.1
+            files: |
+              YoutubetoPremiere.pkg
 
   win-build:
     #needs: mac-build
