Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -375,10 +375,22 @@ jobs:
       run: |
         choco install nsis
 
-    - name: Download NSExec plugin
+    - name: Download and Install NSExec plugin
       run: |
           curl -L https://nsis.sourceforge.io/mediawiki/images/1/18/NsExec.zip -o NsExec.zip
-          Expand-Archive -Path NsExec.zip -DestinationPath $Env:ProgramFiles\NSIS\Plugins\x86-unicode
+          if ($LASTEXITCODE -ne 0) { 
+              Write-Error "Error downloading NSExec.zip"
+              exit $LASTEXITCODE
+          }
+          try {
+              Expand-Archive -Path NsExec.zip -DestinationPath $Env:ProgramFiles\NSIS\Plugins\x86-unicode -Force
+          } catch {
+              Write-Error "Error expanding NSExec.zip: $_"
+              exit 1
+          }
+      shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
+      env:
+        pythonLocation: C:\hostedtoolcache\windows\Python\3.8.8\x64
     
     - name: Create NSIS Script
       run: |
