Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -147,20 +147,21 @@ jobs:
         
     - name: Sign the Application
       run: |
-          # Extract the name of the certificate
-          security find-identity -v -p codesigning $KEYCHAIN_PATH
-
-          # Extract the name of the certificate
-          CERTIFICATE_NAME="$(security find-identity -v -p codesigning $KEYCHAIN_PATH | grep 'Developer ID Application: mickael ducatez' | awk -F '"' '{print $2}')"
-          
-          # Check if certificate name was extracted
-          if [ -z "$CERTIFICATE_NAME" ]; then
-            echo "Certificate name not found"
-            exit 1
-          fi
-          
-          # Use the certificate name to sign the application
-          codesign --deep --force --verify --verbose --sign "$CERTIFICATE_NAME" --keychain $KEYCHAIN_PATH "dist/YoutubetoPremiere.app"
+        # Extract the name of the certificate
+        CERTIFICATE_NAME="$(security find-identity -v -p codesigning $KEYCHAIN_PATH | grep 'Developer ID Application: mickael ducatez' | awk -F '"' '{print $2}')"
+    
+        # Print the extracted certificate name for debugging
+        echo "Certificate Name: $CERTIFICATE_NAME"
+    
+        # Check if certificate name was extracted
+        if [ -z "$CERTIFICATE_NAME" ]; then
+          echo "Certificate name not found"
+          exit 1
+        fi
+    
+        # Use the certificate name to sign the application
+        codesign --deep --force --verify --verbose --sign "$CERTIFICATE_NAME" --keychain $KEYCHAIN_PATH "dist/YoutubetoPremiere.app"
+    
 
 
     - name: List Executable
