Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -333,9 +333,6 @@ jobs:
       with:
         python-version: 3.8.8
         architecture: x64
-      env:
-        DYLD_LIBRARY_PATH: /opt/homebrew/opt/gettext/lib:$DYLD_LIBRARY_PATH
-        PATH: /opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/gnu-tar/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
 
     - name: Sync clock
       run: sudo sntp -sS time.windows.com
@@ -343,15 +340,18 @@ jobs:
     - name: Verify gettext installation
       run: ls -la $(brew --prefix gettext)/lib
 
-    - name: Set DYLD_LIBRARY_PATH
-      run: echo "DYLD_LIBRARY_PATH=$(brew --prefix gettext)/lib:\$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
-
     - name: Upgrade pip
       run: python -m pip install --upgrade pip setuptools wheel
 
+    - name: Check for requirements.txt
+      run: |
+        if [ ! -f requirements.txt ]; then
+          echo "requirements.txt not found"
+          exit 1
+        fi
+
     - name: Install dependencies
       run: pip install -r requirements.txt
-
 
     - name: Create and Configure Keychain
       env:
