Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -107,6 +107,36 @@ jobs:
           echo "FFmpeg execution path: $EXEC_PATH"
           find "$EXEC_PATH" \( -name "*.dylib" -or -name "*.so" -or -name "ffmpeg" \) -exec codesign --timestamp --options runtime --force --verify --verbose --sign "Developer ID Application: mickael ducatez (9H8DB46V75)" {} \;
 
+    - name: "Notarize app bundle"
+      env:
+            MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.APPLE_ID }}
+            MACOS_NOTARIZATION_PWD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
+            MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
+      run: |
+            echo "Create keychain profile"
+            xcrun notarytool store-credentials "notarytool-profile" --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --team-id "$MACOS_NOTARIZATION_TEAM_ID" --password "$MACOS_NOTARIZATION_PWD"
+    
+            echo "Creating temp notarization archive"
+            ditto -c -k --keepParent "./pkgroot/ffmpeg" "notarization.zip"
+    
+            echo "Notarize app"
+            NOTARIZATION_OUTPUT=$(xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait --output-format json)
+            NOTARIZATION_ID=$(echo "$NOTARIZATION_OUTPUT" | jq -r '.id')
+            
+            if [[ $NOTARIZATION_ID == "null" ]]; then
+                echo "Notarization submission failed."
+                echo "Output: $NOTARIZATION_OUTPUT"
+                exit 1
+            fi
+    
+            # Check Notarization Status
+            echo "Checking Notarization Status for $NOTARIZATION_ID"
+            xcrun notarytool info $NOTARIZATION_ID --keychain-profile "notarytool-profile"
+    
+            # Fetch and display the notarization log
+            echo "Fetching notarization log for $NOTARIZATION_ID..."
+            xcrun notarytool log $NOTARIZATION_ID --keychain-profile "notarytool-profile"
+    
     - name: Set DYLD_LIBRARY_PATH
       run: |
                 echo "Setting DYLD_LIBRARY_PATH to include Python library path"
