Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -41,6 +41,11 @@ jobs:
           brew install ffmpeg
         fi
 
+    - name: Find ffmpeg
+      run: |
+        find ./ -name "ffmpeg" -type f -exec echo "Found ffmpeg at: {}" \;
+
+
     - name: Install PyInstaller
       run: pip install pyinstaller
 
@@ -61,6 +66,20 @@ jobs:
         YoutubetoPremiere.py
 
 
+    - name: Prepare PymiereLink and Installation Script
+      run: |
+        mkdir -p "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink"
+        cp -R "/path/to/PymiereLink" "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink"
+        cp "install_pymierelink.sh" "./dist/YoutubetoPremiere.app/Contents/Resources/"
+
+        if [ -f "./dist/YoutubetoPremiere.app/Contents/MacOS/YoutubetoPremiere" ]; then
+          mv "./dist/YoutubetoPremiere.app/Contents/MacOS/YoutubetoPremiere" "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink/exec"
+        else
+          echo "Executable not found. Check PyInstaller build process."
+          exit 1
+        fi
+
+
     - name: Prepare FFmpeg directory
       run: |
           mkdir -p "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink/exec/"
@@ -75,18 +94,7 @@ jobs:
             exit 1
           fi
 
-    - name: Prepare PymiereLink and Installation Script
-      run: |
-        mkdir -p "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink"
-        cp -R "/path/to/PymiereLink" "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink"
-        cp "install_pymierelink.sh" "./dist/YoutubetoPremiere.app/Contents/Resources/"
 
-        if [ -f "./dist/YoutubetoPremiere.app/Contents/MacOS/YoutubetoPremiere" ]; then
-          mv "./dist/YoutubetoPremiere.app/Contents/MacOS/YoutubetoPremiere" "./dist/YoutubetoPremiere.app/Contents/Resources/PymiereLink/exec"
-        else
-          echo "Executable not found. Check PyInstaller build process."
-          exit 1
-        fi
 
     - name: Create macOS Package
       run: |
