Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -201,34 +201,31 @@ jobs:
               codesign --deep --timestamp --options runtime --force --verify --verbose --sign "Developer ID Application: mickael ducatez (9H8DB46V75)" "./dist/YoutubetoPremiere"
               codesign --deep --timestamp --options runtime --force --verify --verbose --sign "Developer ID Application: mickael ducatez (9H8DB46V75)" "./dist/YoutubetoPremiere/YoutubetoPremiere"          
 
-
     - name: "Notarize app bundle"
       env:
-        MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.APPLE_ID }}
-        MACOS_NOTARIZATION_PWD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
-        MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
+                MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.APPLE_ID }}
+                MACOS_NOTARIZATION_PWD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
+                MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
       run: |
-        echo "Create keychain profile"
-        xcrun notarytool store-credentials "notarytool-profile" --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --team-id "$MACOS_NOTARIZATION_TEAM_ID" --password "$MACOS_NOTARIZATION_PWD"
-
-        echo "Creating temp notarization archive"
-        ditto -c -k --keepParent "./dist/YoutubetoPremiere" "notarization.zip"
-
-        echo "Notarize app"
-        NOTARIZATION_OUTPUT=$(xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait --output-format json)
-        NOTARIZATION_ID=$(echo "$NOTARIZATION_OUTPUT" | jq -r '.id')
-        
-        if [[ $NOTARIZATION_ID == "null" ]]; then
-            echo "Notarization submission failed."
-            echo "Output: $NOTARIZATION_OUTPUT"
-            exit 1
-        fi
-
-        echo "Attach staple"
-        xcrun stapler staple "./dist/YoutubetoPremiere"
-
-    
-
+                echo "Create keychain profile"
+                xcrun notarytool store-credentials "notarytool-profile" --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --team-id "$MACOS_NOTARIZATION_TEAM_ID" --password "$MACOS_NOTARIZATION_PWD"
+            
+                echo "Creating temp notarization archive"
+                ditto -c -k --keepParent "./dist/YoutubetoPremiere" "notarization.zip"
+            
+                echo "Notarize app"
+                NOTARIZATION_OUTPUT=$(xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait --output-format json)
+                NOTARIZATION_ID=$(echo "$NOTARIZATION_OUTPUT" | jq -r '.id')
+                
+                if [[ $NOTARIZATION_ID == "null" ]]; then
+                    echo "Notarization submission failed."
+                    echo "Output: $NOTARIZATION_OUTPUT"
+                    exit 1
+                fi
+            
+                echo "Attach staple"
+                xcrun stapler staple "./dist/YoutubetoPremiere"
+            
     - name: Prepare PKG content
       run: |
         mkdir pkgroot
