Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,7 @@ jobs:
     steps:
 
     - name: Checkout code
-      uses: actions/checkout@v4
+      uses: actions/checkout@v2
 
 
     - name: Set up Python
@@ -180,7 +180,6 @@ jobs:
       run: |
           find ./dist -type f -exec codesign --timestamp --options runtime --force --verify --verbose --sign "Developer ID Application: mickael ducatez (9H8DB46V75)" {} \;
 
-
         
     - name: Sign the Application
       run: |
@@ -203,58 +202,31 @@ jobs:
               codesign --deep --timestamp --options runtime --force --verify --verbose --sign "Developer ID Application: mickael ducatez (9H8DB46V75)" "./dist/YoutubetoPremiere/YoutubetoPremiere"          
 
 
-    - name: "Notarize executable"
+    - name: "Notarize app bundle"
       env:
-                PROD_MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.APPLE_ID }}
-                PROD_MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
-                PROD_MACOS_NOTARIZATION_PWD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
+        MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.APPLE_ID }}
+        MACOS_NOTARIZATION_PWD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
+        MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
       run: |
-                # Store the notarization credentials
-                echo "Create keychain profile"
-                xcrun notarytool store-credentials "notarytool-profile" --apple-id "${{ secrets.APPLE_ID }}" --team-id "${{ secrets.APPLE_TEAM_ID }}" --password "${{ secrets.APP_SPECIFIC_PASSWORD }}"
-              
-                ls -R ./dist
+        echo "Create keychain profile"
+        xcrun notarytool store-credentials "notarytool-profile" --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --team-id "$MACOS_NOTARIZATION_TEAM_ID" --password "$MACOS_NOTARIZATION_PWD"
 
-                # Create a ZIP file of the executable for notarization
-                echo "Creating temp notarization archive"
-                ditto -c -k --keepParent "./dist/YoutubetoPremiere" "notarization.zip"
+        echo "Creating temp notarization archive"
+        ditto -c -k --keepParent "./dist/YoutubetoPremiere" "notarization.zip"
 
+        echo "Notarize app"
+        NOTARIZATION_OUTPUT=$(xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait --output-format json)
+        NOTARIZATION_ID=$(echo "$NOTARIZATION_OUTPUT" | jq -r '.id')
+        
+        if [[ $NOTARIZATION_ID == "null" ]]; then
+            echo "Notarization submission failed."
+            echo "Output: $NOTARIZATION_OUTPUT"
+            exit 1
+        fi
 
-              
-                # Send the notarization request and capture the NOTARIZATION_ID
-                echo "Notarize executable"
-                NOTARIZATION_OUTPUT=$(xcrun notarytool submit "notarization.zip" --keychain-profile "notarytool-profile" --wait --output-format json)
-                NOTARIZATION_ID=$(echo "$NOTARIZATION_OUTPUT" | jq -r '.id')
-                echo "Notarization ID: $NOTARIZATION_ID"
-                echo "NOTARIZATION_ID=$NOTARIZATION_ID" >> $GITHUB_ENV
-              
-                # Check if submission was successful
-                if [ "$NOTARIZATION_ID" = "null" ]; then
-                    echo "Notarization submission failed."
-                    echo "Output: $NOTARIZATION_OUTPUT"
-                    exit 1
-                fi
-              
-                # Fetch Notarization Info
-                echo "Fetching Notarization Info"
-                NOTARIZATION_INFO=$(xcrun notarytool info $NOTARIZATION_ID --keychain-profile "notarytool-profile" --output-format json)
-                echo "Notarization Info: $NOTARIZATION_INFO"
-              
-                # Fetch and display the notarization log
-                echo "Fetching notarization log..."
-                xcrun notarytool log $NOTARIZATION_ID --keychain-profile "notarytool-profile"
-              
-                if [[ $NOTARIZATION_INFO == *"\"status\":\"Accepted\""* ]]; then
-                    echo "Executable successfully notarized."
-                else
-                    echo "Notarization failed."
-                    exit 1
-                fi
-      shell: /bin/bash -e {0}
+        echo "Attach staple"
+        xcrun stapler staple "./dist/YoutubetoPremiere"
 
-    - name: Verify Code Signature
-      run: |
-        codesign --verify --deep --strict ./dist/YoutubetoPremiere
     
 
     - name: Prepare PKG content
