Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -115,7 +115,7 @@ jobs:
             # create variables
             CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
             PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
-            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+            KEYCHAIN_PATH=$RUNNER_TEMP/SelgykeyAPP.keychain-db
 
             # import certificate and provisioning profile from secrets
             echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
@@ -125,18 +125,19 @@ jobs:
             security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
             security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
             security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+            
 
             # import certificate to keychain
-            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH || echo "Certificate import failed"
+            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
             security list-keychain -d user -s $KEYCHAIN_PATH
 
             # Apply provisioning profile
             mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
             cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
 
-            # List all certificates to verify import
-            echo "Listing all certificates in keychain:"
-            security find-certificate -a /Users/runner/Library/Keychains/build.keychain-db
+            security find-certificate -a $KEYCHAIN_PATH
+            security find-identity -p codesigning $KEYCHAIN_PATH
+            
 
             # List all identities (not just valid ones) to check the certificate
             echo "Listing all identities in keychain:"
@@ -146,15 +147,17 @@ jobs:
         
     - name: Sign the Application
       run: |
-        # List identities and find the correct one
-        security find-identity -v -p codesigning /Users/runner/Library/Keychains/build.keychain-db
-  
-        # Extract the name of the certificate (modify this line as needed)
-        CERTIFICATE_NAME="$(security find-identity -v -p codesigning /Users/runner/Library/Keychains/build.keychain-db | grep 'certificate.p12' | awk '{print $3}')"
-  
-        # Use the certificate name to sign the application
-        codesign --deep --force --verify --verbose --sign "$CERTIFICATE_NAME" --keychain /Users/runner/Library/Keychains/build.keychain-db "dist/YoutubetoPremiere.app"
+          # Extract the name of the certificate
+          CERTIFICATE_NAME="$(security find-identity -v -p codesigning $KEYCHAIN_PATH | grep 'developer ID Application: mickael ducatez (9H8DB46V75)' | awk '{print $2}')"
 
+          # Check if certificate name was extracted
+          if [ -z "$CERTIFICATE_NAME" ]; then
+            echo "Certificate name not found"
+            exit 1
+          fi
+
+          # Use the certificate name to sign the application
+          codesign --deep --force --verify --verbose --sign "$CERTIFICATE_NAME" --keychain $KEYCHAIN_PATH "dist/YoutubetoPremiere.app"
 
 
     - name: List Executable
@@ -247,10 +250,12 @@ jobs:
             tag_name: V1.1
             files: |
               YoutubetoPremiere.pkg
+
+
     - name: Clean up keychain and provisioning profile
       if: ${{ always() }}
       run: |
-        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
+        security delete-keychain $KEYCHAIN_PATH
         rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
 
 
